### ISSUE TITLE
Something's wrong.

### ISSUE THREAD

**Issue by Njordy** [hrqmonteiro/joplin-theme#2]
Tried it both on linux and windows. Latest version. installed the font what were suggested. Dunno, things are messed up. In another thread I've seen something about new version, maybe it doesn't suppose to work anymore

**Comment by hrqmonteiro** [comment]
> Tried it both on linux and windows. Latest version. installed the font what were suggested. Dunno, things are messed up. In another thread I've seen something about new version, maybe it doesn't suppose to work anymore

Hello @Njordy 

Yes, this is for the previous Joplin appearance, it changed a few versions ago, which came out in november, i guess. So the theme doesn't work in the current version, that's why it should be all messed up.

As i said i intend to update the theme to the current Joplin version is just that i am so loaded with college and work that i couldn't stop for a while and work on it. For now i myself am using the default 'Aritin Dark' theme for now.

**Comment by vishnuugopi** [comment]
That's a shame, let us know once you've got around to fixing it.
